### ISSUE TITLE
World age errors in Julia 1.12

### ISSUE THREAD

**Issue by jacobleft** [BioTurboNick/AbbreviatedStackTraces.jl#75]
## 1. Error if immediately set `JULIA_STACKTRACE_ABBREVIATED`
```shell
➜ julia +1.12 --startup-file=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.2 (2025-11-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org release
|__/                   |

(@v1.12) pkg> activate --temp
  Activating new project at `/var/folders/n0/367fnn5x0rg8p83b918ltdph0000gn/T/jl_HiOiUS`

(jl_HiOiUS) pkg> add AbbreviatedStackTraces
   Resolving package versions...
    Updating `/private/var/folders/n0/367fnn5x0rg8p83b918ltdph0000gn/T/jl_HiOiUS/Project.toml`
  [ac637c84] + AbbreviatedStackTraces v0.3.2
    Updating `/private/var/folders/n0/367fnn5x0rg8p83b918ltdph0000gn/T/jl_HiOiUS/Manifest.toml`
  [ac637c84] + AbbreviatedStackTraces v0.3.2
  ? AbbreviatedStackTraces

julia> using AbbreviatedStackTraces
  ? AbbreviatedStackTraces
[ Info: Precompiling AbbreviatedStackTraces [ac637c84-cc71-43bf-9c33-c1b4316be3d4]
┌ Info: Skipping precompilation due to precompilable error. Importing AbbreviatedStackTraces [ac637c84-cc71-43bf-9c33-c1b4316be3d4].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.

julia> ENV["JULIA_STACKTRACE_ABBREVIATED"] = true
Error showing value of type Bool:

SYSTEM (REPL): showing an error caused an error
ERROR: 1-element ExceptionStack:
MethodError: no method matching (::AbbreviatedStackTraces.AbbrvStackTracesREPLExt.var"#3#4")()
The applicable method may be too new: running in world age 38660, while current world is 38811.

Closest candidates are:
  (::AbbreviatedStackTraces.AbbrvStackTracesREPLExt.var"#3#4")() (method too new to be called from this world context.)
   @ AbbreviatedStackTraces ~/.julia/packages/AbbreviatedStackTraces/yF1iS/ext/AbbrvStackTracesREPLExt.jl:30

Some frames were hidden. Use `show(err)` to see complete trace.
```
## 2. Error if there is previously displayed errors
```shell
➜ julia +1.12 --startup-file=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.2 (2025-11-20)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org release
|__/                   |

(@v1.12) pkg> activate --temp
  Activating new project at `/var/folders/n0/367fnn5x0rg8p83b918ltdph0000gn/T/jl_VPeWqR`

(jl_VPeWqR) pkg> add AbbreviatedStackTraces
   Resolving package versions...
    Updating `/private/var/folders/n0/367fnn5x0rg8p83b918ltdph0000gn/T/jl_VPeWqR/Project.toml`
  [ac637c84] + AbbreviatedStackTraces v0.3.2
    Updating `/private/var/folders/n0/367fnn5x0rg8p83b918ltdph0000gn/T/jl_VPeWqR/Manifest.toml`
  [ac637c84] + AbbreviatedStackTraces v0.3.2
  ? AbbreviatedStackTraces

julia> using AbbreviatedStackTraces
  ? AbbreviatedStackTraces
[ Info: Precompiling AbbreviatedStackTraces [ac637c84-cc71-43bf-9c33-c1b4316be3d4]
┌ Info: Skipping precompilation due to precompilable error. Importing AbbreviatedStackTraces [ac637c84-cc71-43bf-9c33-c1b4316be3d4].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.

(jl_VPeWqR) pkg> sin
ERROR: `sin` is not a recognized command. Type ? for help with available commands

help?> sin
search: sin sign sinh sind asin sinc in min isinf asinh sinpi asind using stdin size skip sprint Main sincos join bind string Cint

Error showing value of type Markdown.MD:

SYSTEM (REPL): showing an error caused an error
ERROR: 1-element ExceptionStack:
MethodError: no method matching (::AbbreviatedStackTraces.AbbrvStackTracesREPLExt.var"#3#4")()
The applicable method may be too new: running in world age 38660, while current world is 38812.

Closest candidates are:
  (::AbbreviatedStackTraces.AbbrvStackTracesREPLExt.var"#3#4")() (method too new to be called from this world context.)
   @ AbbreviatedStackTraces ~/.julia/packages/AbbreviatedStackTraces/yF1iS/ext/AbbrvStackTracesREPLExt.jl:30

Some frames were hidden. Use `show(err)` to see complete trace.
```

**Comment by BioTurboNick** [comment]
Huh. Weird. Let me see about this.

**Comment by BioTurboNick** [comment]
Should be fixed in v0.3.3, in the Registry queue.

**Comment by BioTurboNick** [comment]
FWIW, it was more general than this - the REPL display value path was broken. Not sure why, maybe the world age semantics were changed between 1.12-alpha and the rc, and I didn't know.

**Comment by cstjean** [comment]
FWIW I just hit this issue (on 1.12.2, Windows), and upgrading to 0.3.3 did not solve it for me.

**Comment by BioTurboNick** [comment]
Damnit.

**Comment by BioTurboNick** [comment]
Whew, figured it out. Almost thought there was no solution.

The root cause is that `print_response` function passes an anonymous function to the `repl_backend_loop` function in order to invoke the display method on the REPL thread, in the world age at that time. That loop starts running when Julia starts up. Any functions defined after the REPL starts increments the world age. So this new function in a newer world is passed back to the loop which is in an older world to execute. But this is illegal in 1.12.

BUT! Turns out that I no longer needed to overwrite `print_response` as of 1.11. Dropping that code in 1.11+ allows it to work!

v0.3.4 on the way
